1. Import libraries

In [28]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from bs4 import BeautifulSoup # library to parse HTML and XML documents

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans


print("Libraries imported.")

Libraries imported.

2. Scrap data from Wikipedia page into a DataFrame

In [3]:
data = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [4]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

In [5]:
# create three lists to store table data
postalCodeList = []
boroughList = []
neighborhoodList = []

Using BeautifulSoup

# find the table
soup.find('table').find_all('tr')

# find all the rows of the table
soup.find('table').find_all('tr')

# for each row of the table, find all the table data
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')

In [6]:
# append the data into the respective lists
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')
    if(len(cells) > 0):
        postalCodeList.append(cells[0].text)
        boroughList.append(cells[1].text)
        neighborhoodList.append(cells[2].text.rstrip('\n')) # avoid new lines in neighborhood cell

In [7]:
# create a new DataFrame from the three lists
toronto_df = pd.DataFrame({"PostalCode": postalCodeList,
                           "Borough": boroughList,
                           "Neighborhood": neighborhoodList})

toronto_df.head()

  PostalCode             Borough               Neighborhood
0      M1A\n      Not assigned\n               Not assigned
1      M2A\n      Not assigned\n               Not assigned
2      M3A\n        North York\n                  Parkwoods
3      M4A\n        North York\n           Victoria Village
4      M5A\n  Downtown Toronto\n  Regent Park, Harbourfront

3. Drop cells with a borough that is "Not assigned"

In [18]:
# drop cells with a borough that is Not assigned
toronto_df_dropna = toronto_df[toronto_df.Borough != "Not assigned\n"].reset_index(drop=True)

In [19]:
toronto_df_dropna.head()

  PostalCode             Borough                                 Neighborhood
0      M3A\n        North York\n                                    Parkwoods
1      M4A\n        North York\n                             Victoria Village
2      M5A\n  Downtown Toronto\n                    Regent Park, Harbourfront
3      M6A\n        North York\n             Lawrence Manor, Lawrence Heights
4      M7A\n  Downtown Toronto\n  Queen's Park, Ontario Provincial Government

4. Group neighborhoods in the same borough

In [23]:
# group neighborhoods in the same borough
toronto_df_grouped = toronto_df_dropna.groupby(["PostalCode", "Borough"], as_index=False).agg(lambda x: ", ".join(x))
toronto_df_grouped.head()

  PostalCode        Borough                            Neighborhood
0      M1B\n  Scarborough\n                          Malvern, Rouge
1      M1C\n  Scarborough\n  Rouge Hill, Port Union, Highland Creek
2      M1E\n  Scarborough\n       Guildwood, Morningside, West Hill
3      M1G\n  Scarborough\n                                  Woburn
4      M1H\n  Scarborough\n                               Cedarbrae

5. For Neighborhood="Not assigned", make the value the same as Borough

In [24]:
# for Neighborhood="Not assigned", make the value the same as Borough
for index, row in toronto_df_grouped.iterrows():
    if row["Neighborhood"] == "Not assigned\n":
        row["Neighborhood"] = row["Borough"]
        
toronto_df_grouped.head()

  PostalCode        Borough                            Neighborhood
0      M1B\n  Scarborough\n                          Malvern, Rouge
1      M1C\n  Scarborough\n  Rouge Hill, Port Union, Highland Creek
2      M1E\n  Scarborough\n       Guildwood, Morningside, West Hill
3      M1G\n  Scarborough\n                                  Woburn
4      M1H\n  Scarborough\n                               Cedarbrae

6. Check whether it is the same as required by the question

In [25]:
# create a new test dataframe
column_names = ["PostalCode", "Borough", "Neighborhood"]
test_df = pd.DataFrame(columns=column_names)

test_list = ["M5G\n", "M2H\n", "M4B\n", "M1J\n", "M4G\n", "M4M\n", "M1R\n", "M9V\n", "M9L\n", "M5V\n", "M1B\n", "M5A\n"]

for postcode in test_list:
    test_df = test_df.append(toronto_df_grouped[toronto_df_grouped["PostalCode"]==postcode], ignore_index=True)
    
test_df

,PostalCode,Borough,Neighborhood
0,M5G\n,Downtown Toronto\n,Central Bay Street
1,M2H\n,North York\n,Hillcrest Village
2,M4B\n,East York\n,"Parkview Hill, Woodbine Gardens"
3,M1J\n,Scarborough\n,Scarborough Village
4,M4G\n,East York\n,Leaside
5,M4M\n,East Toronto\n,Studio District
6,M1R\n,Scarborough\n,"Wexford, Maryvale"
7,M9V\n,Etobicoke\n,"South Steeles, Silverstone, Humbergate, Jamest..."
8,M9L\n,North York\n,Humber Summit
9,M5V\n,Downtown Toronto\n,"CN Tower, King and Spadina, Railway Lands, Har..."
10,M1B\n,Scarborough\n,"Malvern, Rouge"
11,M5A\n,Downtown Toronto\n,"Regent Park, Harbourfront"

In [27]:
print(test_df.shape)

(12, 3)